sudo: true
dist: trusty
language: cpp

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - cmake
      - libopencv-dev
      - libqt4-dev
      - libsqlite3-dev

install:
    - "sudo apt-get install libpcl-1.7-all libfreenect-dev"

script: 
    - mkdir -p build && cd build
    - cmake .. 
    - make
